version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: weekly
    directory: /
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"